## Group 3 Week 5

1. Consider the fixed-point iteration described by
    $$
    \begin{aligned}
    x_{n+1}= g( x_n)=\frac{1}{2}\left(x_n+\frac{a^2}{x_n}\right)\end{aligned}
    $$
    Show that the iteration converges to $a$ for any initial point $x_1 > 0$, and that the convergence is quadratic.

2. A particle of mass $m$ is bound within a 1-D square well of radius $a$
    $$
    V\left(  x\right)  =\begin{cases}
    -V_{0}, & \text{for }\left\vert x\right\vert \leq a,\\
    0, & \text{for }\left\vert x\right\vert \geq a
    \end{cases}
    $$
    Quantum Mechanics shows that the energies of the bound states $E<0$ are solutions of the transcendental equations
    $$
    \begin{aligned}
    \sqrt{10+E}\tan\left(  \sqrt{10+E}\right)    & =\sqrt{-E}\;\left(
    \text{even}\right)  \\
    \sqrt{10+E}\cot\left(  \sqrt{10+E}\right)    & =-\sqrt{-E}\;\left(  \text{odd}\right)\end{aligned}
    $$
    where even and odd refer to the symmetry of the wave function. Here we have chosen units such that $\hbar=1,$ $2m=1,$ $a=1$, and $V_{0}=10.$

    a) Find several bound-state energies for even wave function.

    b) See if making the potential deeper, say, by changing the 10 to a 20, or a 30, produces a larger number of, or deeper bound states. Also make the potential shallower, and see how the energies change. Please make a diagram of the ground state energy versus the depth of the potential.

3. Find the bond length of NaCl using the potential model discussed in the lecture, 
    $$
    V(r)=-\frac{e^2}{r}+V_0\exp(-r/r_0)
    $$
    Please use $e^2=14.4$ $\text{Å}\cdot eV$, $V_0=1.09\times 10^3 \text{ eV}$, $r_0=0.330\text{ Å}$. Write your own program and compare your result with the results from Python package `scipy.optimize`[^1]

In [1]:
import numpy as np

def bic(f,left,right):   #二分法求根的大概范围
    while True:
        if abs(left - right) / abs(right + left ) < 1e-6:
            return left,right
        elif f(left)*f((right + left)/2 ) > 0:
            left = (left+right)/2
        else:
            right = (left+right)/2

def secant(f,x0,x1):     #范围精度够高后换secant算法收敛更快
    count = 30
    while abs(x0-x1)>1e-16:
        x2 = x1 - f(x1)*(x1-x0)/(f(x1)-f(x0))
        x0 = x1
        x1 = x2
        count = count - 1
        if count == 0:
            break
    return x1
            
V = lambda r: - 14.4/r + 1.09e3*np.exp(-r/0.330)
V_star = lambda r: 14.4/r - 1.09e3*np.exp(-r/0.330)
V1 = lambda r: 14.4 / (r*r) - 1.09e3/0.330*np.exp(-r/0.330)

x = secant(V1,bic(V1,0.01,0.1)[0],bic(V1,0.01,0.1)[1])
print(f'x = {x}')

import scipy.optimize as sco
result = sco.minimize(V_star,0.04)
print(f'x from scipy:{result.x[0]:.16}')

error_r = abs(x - result.x[0])/(x + result.x[0])
print(f'relative error = {error_r}')
print('将给出的x带入到导数里：')
print(f'V1(x_calc) = {V1(x)}')
print(f'V1(x_scipy) = {V1(result.x[0])}')

x = 0.0738441389366838
x from scipy:0.07384413149617723
relative error = 5.037980707722287e-08
将给出的x带入到导数里：
V1(x_calc) = 4.547473508864641e-13
V1(x_scipy) = 0.0004726244119410694


4. Consider the nonlinear system 
    $$
    \begin{cases}
    2e^x+y=0\\
    3x^2+4y^2=8
    \end{cases}
    $$
    a) Locate the roots graphically.

    b) Based on the location of the roots, find the roots and compare your numerical results with the results from Python package `scipy.optimize`[^1]

    [^1]: (https://docs.scipy.org/doc/scipy/reference/optimize.html).

5. Consider a linear $2\times 2$ system (with unknowns $x_1$ and $x_2$) described by its augmented matrix 
    $$
    \begin{bmatrix}
    \left.\begin{matrix}\varepsilon & 1\\
    1 & 1
    \end{matrix}\right\vert
    \begin{matrix}
    2\\
    1
    \end{matrix}\end{bmatrix}
    $$
    where $\epsilon > 0$ is a very small constant.

    a) Solve by Gauss elimination without partial pivoting.

    b) Solve by Gauss elimination with partial pivoting. Compare the results and discuss their validity.



a)
$$
\left[
\begin{matrix}
1 & 0\\
-\frac{1}{\varepsilon} & 1
\end{matrix}
\right]
\begin{bmatrix}
\left.\begin{matrix}\varepsilon & 1\\
1 & 1
\end{matrix}\right\vert
\begin{matrix}
2\\
1
\end{matrix}\end{bmatrix} = 
\begin{bmatrix}
\left.\begin{matrix}\varepsilon & 1\\
0 & 1-\frac{1}{\varepsilon}
\end{matrix}\right\vert
\begin{matrix}
2\\
1 - \frac{2}{\varepsilon}
\end{matrix}\end{bmatrix}
$$
we get:
$$
x1 = \frac{1-\frac{2}{\varepsilon} }{1-\frac{1}{\varepsilon}},\quad x0= \left(2 - \frac{1-\frac{2}{\varepsilon} }{1-\frac{1}{\varepsilon}}\right)/\varepsilon = (2-x1)/\varepsilon
$$

In [5]:
# try with code
for i in range(3):
    eps = float(input('input a small constant:'))
    x1 = (1 - 2/eps )/(1 - 1/eps )
    x0 = (2 - x1) / eps
    print(f'x0 = {x0},  x1 = {x1}')
    M = np.matrix([[eps,1],[1,1]])
    X = np.matrix([[x0],[x1]])
    print(f'M*X = ')
    print(M@X)

input a small constant: 1e-5


x0 = -1.0000100000961964,  x1 = 2.000010000100001
M*X = 
[[2.]
 [1.]]


input a small constant: 1e-10


x0 = -1.000000082740371,  x1 = 2.0000000001
M*X = 
[[2.        ]
 [0.99999992]]


input a small constant: 1e-15


x0 = -0.8881784197001251,  x1 = 2.000000000000001
M*X = 
[[2.        ]
 [1.11182158]]


b)
$$
\left[\begin{matrix}
0 & 1\\
1 & 0
\end{matrix}\right] \begin{bmatrix}
\left.\begin{matrix}\varepsilon & 1\\
1 & 1
\end{matrix}\right\vert
\begin{matrix}
2\\
1
\end{matrix}\end{bmatrix} = 
\begin{bmatrix}
\left.\begin{matrix}1 & 1\\
\varepsilon & 1
\end{matrix}\right\vert
\begin{matrix}
1\\
2
\end{matrix}\end{bmatrix}
$$

$$
\left[\begin{matrix}
1 & 0\\
-\varepsilon & 1
\end{matrix}\right] \begin{bmatrix}
\left.\begin{matrix}1 & 1\\
\varepsilon & 1
\end{matrix}\right\vert
\begin{matrix}
1\\
2
\end{matrix}\end{bmatrix} = 
\begin{bmatrix}
\left.\begin{matrix}1 & 1\\
0 & 1 - \varepsilon
\end{matrix}\right\vert
\begin{matrix}
1\\
2 - \varepsilon
\end{matrix}\end{bmatrix}
$$

so get
$$
x1 = \frac{2-\varepsilon}{1-\varepsilon},\quad x0 = 1 - x1
$$

In [9]:
# try with code
for i in range(3):
    eps = float(input('input a small constant:'))
    x1 = (2 - eps )/(1 - eps )
    x0 = 1 - x1
    print(f'x0 = {x0},  x1 = {x1}')
    M = np.matrix([[eps,1],[1,1]])
    X = np.matrix([[x0],[x1]])
    print(f'M*X = ')
    print(M@X)

input a small constant: 1e-5


x0 = -1.000010000100001,  x1 = 2.000010000100001
M*X = 
[[2.]
 [1.]]


input a small constant: 1e-10


x0 = -1.0000000001,  x1 = 2.0000000001
M*X = 
[[2.]
 [1.]]


input a small constant: 1e-15


x0 = -1.0000000000000009,  x1 = 2.000000000000001
M*X = 
[[2.]
 [1.]]


不选主元可以看到反过来求$MX$的值随着$\varepsilon$的变小误差越来越大，取主元后，不在有这样的现象。不取主元的截断误差被反大了，显然取主元的方法更有效

6. Solve the system of equations $Ax=b$ with a well-behaved matrix
    $$
    A_{ii}=n,\text{ }A_{i\neq j}=1
    $$
    by applying 

    a) LU decomposition, (Hint: You can use Python module `scipy.linalg.lu_solve`)

    b) Cholesky decomposition, (Hint: You can use Python module `numpy.linalg.cholesky`)

    The right-hand side is $b=A\begin{pmatrix}
    1\\
    2\\
    \vdots\\
    n
    \end{pmatrix}$, hence the exact solution is $x=\begin{pmatrix}
    1\\
    2\\
    \vdots\\
    n
    \end{pmatrix}$.



7. **Multiple linear regression** generalizes simple linear regression by allowing several predictor variables instead of just one.    
   We model the response $y=a_{0}+a_{1}x_{1}+\cdots+a_{p}x_{p}$. Now, we have a sequence of $n$ response values $y_{i}$, and a sequence of $n$ predictor vectors $(x_{i1},x_{i2},\cdots,x_{ip})$. The goal is to estimate the parameter vector $(a_{0},\cdots,a_{p})$ so as to minimize the sum of the squared errors.   
   In matrix notation, we have an overdetermined system of equations 
   $$
   \mathbf{y=X a}
   $$
   where
   $$
   \begin{pmatrix}
   y_{1}\\
   y_{2}\\
   \vdots\\
   \\
   \\
   y_{n}%
   \end{pmatrix}=\begin{pmatrix}
   1 & x_{11} & x_{12} & \cdots & x_{1p}\\
   1 & x_{21} & x_{22} & \cdots & x_{2p}\\
   \vdots & \vdots & \ddots &  & \vdots\\
   &  &  &  & \\
   1 &  &  &  & \\
   1 & x_{n1} & x_{n2} & \cdots & x_{np}%
   \end{pmatrix} \begin{pmatrix}
   a_{0}\\
   a_{1}\\
   \vdots\\
   \\
   a_{p}%
   \end{pmatrix}
   $$
   Our goal is to find a vector $\mathbf{a}$ that minimizes $\mathbf{Xa-y}$ . A numerically stable algorithm for computing $\mathbf{a}$ is to compute QR factorization $\mathbf{X=QR}$, then solve the triangular system $\mathbf{Ra=Q^{T}y}$ via back substitution.

   The expression $z = ax^{2} +bxy +cy^{2} +dx +ey +f$ is known as a **quadratic form**. The set of points $(x, y)$, where $z = 0$, is a conic section. It can be an ellipse, a parabola, or a hyperbola, depending on the sign of the discriminant $b^{2}-4ac$. Circles and lines are special cases. The equation $z
    = 0$ can be normalized by dividing the quadratic form by any nonzero coefficient. For example, if $f\neq0$, we can divide all the other coefficients by $f$ and obtain a quadratic form with the constant term equal to one.

    ​	A planet follows an elliptical orbit. Here are ten observations of its position in the $(x, y)$ plane:

    ```
    x = [1.02 .95 .87 .77 .67 .56 .44 .30 .16 .01];
    y = [0.39 .32 .27 .22 .18 .15 .13 .12 .13 .15];
    ```

    a) Determine the coefficients in the quadratic form that fits these data in the least squares sense by setting one of the coefficients equal to one and solving a 10-by-5 overdetermined system of linear equations for the other five coefficients. Plot the orbit with $x$ on the $x$-axis and $y$ on the $y$-axis. Superimpose the ten data points on the plot.

    b) This least squares problem is nearly rank deficient. To see what effect this has on the solution, perturb the data slightly by adding to each coordinate of each data point a random number uniformly distributed in the interval $[-.0005, .0005]$. Compute the new coefficients resulting from the perturbed data. Plot the new orbit on the same plot with the old orbit. Comment on your comparison of the sets of coefficients and the orbits.    
    (Hint:  You can use Python module `numpy.linalg.qr`)